- name: Assume Role
  hosts: "{{ env }}"
  gather_facts: no
  roles:
    - aws-sts

- name: Stack Deployment
  hosts: "{{ env }}"
  environment: "{{ Sts.Credentials }}"
  roles:
    - aws-cloudformation
